labels:
  EASY: Easy
  Easy: Easy
  easy: Easy
  1: Easy
  MEDIUM: Moderate
  Medium: Moderate
  Moderate: Moderate
  2: Moderate
  HARD: Hard
  Hard: Hard
  3: Hard
  VERY_HARD: Hard
  Very-Hard: Hard
  Medium-Hard: Hard
